apiVersion: apps/v1
kind: Deployment
metadata:
  name: irsa-v2-594-0
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irsa
  template:
    metadata:
      labels:
        app: irsa
        version: v2-594-0
    spec:
      serviceAccount: my-serviceaccount
      containers:
      - name: irsa
        image: hiprabhat/irsa:2.594.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: irsav2-594-0
  namespace: default
  labels:
    app: irsa
spec:
  selector:
    app: irsa
    version: v2-594-0
  ports:
  - port: 80
    targetPort: 3000
    name: http-irsa

---